Import Libraries

In [52]:
import pandas as pd
import numpy as np

from scipy.sparse import issparse
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler,OneHotEncoder,OrdinalEncoder,StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split,RandomizedSearchCV

from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,f1_score


# Data gathering

In [33]:
def dataLoader(path):
    ds = pd.read_csv(path)
    return ds 


In [34]:
ds = dataLoader('../Data/e_commerce.csv')
ds.shape

(3333, 20)

In [35]:
# split data 

x = ds.drop(['churn'],axis=1)
y = ds['churn']

x


account length  location code  user id credit card info save  \
0                128            415  3824657                    no   
1                107            415  3717191                    no   
2                137            415  3581921                    no   
3                 84            408  3759999                   yes   
4                 75            415  3306626                   yes   
...              ...            ...      ...                   ...   
3328             192            415  4144276                    no   
3329              68            415  3703271                    no   
3330              28            510  3288230                    no   
3331             184            510  3646381                   yes   
3332              74            415  4004344                    no   

     push status  add to wishlist  desktop sessions  app sessions  \
0            yes               25               265            45   
1            yes               26               162            27   
2             no                0               243            41   
3             no                0               299            51   
4             no                0               167            28   
...          ...              ...               ...           ...   
3328         yes               36               156            27   
3329          no                0               231            39   
3330          no                0               181            31   
3331          no                0               214            36   
3332         yes               25               234            40   

      desktop transactions  total product detail views  session duration  \
0                       17                       110.0               197   
1                       17                       123.0               196   
2                       10                       114.0               121   
3                        5                        71.0                62   
4                       13                       113.0               148   
...                    ...                         ...               ...   
3328                    18                        77.0               216   
3329                    13                         NaN               153   
3330                    25                       109.0               289   
3331                    14                       105.0               160   
3332                    23                       113.0               266   

      promotion clicks  avg order value  sale product views  \
0                   87            244.7                  91   
1                  103            254.4                 103   
2                  110            162.6                 104   
3                   88            196.9                  89   
4                  122            186.9                 121   
...                ...              ...                 ...   
3328               126            279.1                  83   
3329                55            191.3                 123   
3330                58            191.9                  91   
3331                84            139.2                 137   
3332                82            241.4                  77   

      discount rate per visited products  product detail view per app session  \
0                                  11.01                                 10.0   
1                                  11.45                                 13.7   
2                                   7.32                                 12.2   
3                                   8.86                                  6.6   
4                                   8.41                                 10.1   
...                                  ...                                  ...   
3328                               12.56                                  9.9   
3329              

In [74]:

cat = x.select_dtypes(include='object').columns
num = x.select_dtypes(exclude='object').columns

cat_pipe = Pipeline(steps=([('impute',SimpleImputer(strategy='most_frequent')),('Encoding',OrdinalEncoder())]))
num_pipe = Pipeline(steps=([('impute',SimpleImputer(strategy='mean')),('scaling',StandardScaler())]))

pipeline = ColumnTransformer([('catPipe',cat_pipe,cat),('numPipe',num_pipe,num)])

x1 = pipeline.fit_transform(x)

if issparse(x1):
    x1 = x1.toarray()
x2 = pd.DataFrame(x1,columns=pipeline.get_feature_names_out())

x2

catPipe__credit card info save  catPipe__push status  \
0                                0.0                   1.0   
1                                0.0                   1.0   
2                                0.0                   0.0   
3                                1.0                   0.0   
4                                1.0                   0.0   
...                              ...                   ...   
3328                             0.0                   1.0   
3329                             0.0                   0.0   
3330                             0.0                   0.0   
3331                             1.0                   0.0   
3332                             0.0                   1.0   

      numPipe__account length  numPipe__location code  numPipe__user id  \
0                    0.676489               -0.523603          0.285359   
1                    0.149065               -0.523603         -0.105965   
2                    0.902529               -0.523603         -0.598534   
3                   -0.428590               -0.688834          0.049915   
4                   -0.654629               -0.523603         -1.600987   
...                       ...                     ...               ...   
3328                 2.283878               -0.523603          1.449212   
3329                -0.830437               -0.523603         -0.156653   
3330                -1.835055                1.718817         -1.667974   
3331                 2.082955                1.718817         -0.363811   
3332                -0.679745               -0.523603          0.939667   

      numPipe__add to wishlist  numPipe__desktop sessions  \
0                     1.234883                   1.564550   
1                     1.307948                  -0.327130   
2                    -0.591760                   1.160502   
3                    -0.591760                   2.188988   
4                    -0.591760                  -0.235301   
...                        ...                        ...   
3328                  2.038605                  -0.437325   
3329                 -0.591760                   0.940112   
3330                 -0.591760                   0.021821   
3331                 -0.591760                   0.627893   
3332                  1.234883                   0.995209   

      numPipe__app sessions  numPipe__desktop transactions  \
0                  1.557193                      -0.020265   
1                 -0.384977                      -0.020265   
2                  1.125600                      -1.639456   
3                  2.204583                      -2.796021   
4                 -0.277078                      -0.945517   
...                     ...                            ...   
3328              -0.384977                       0.211048   
3329               0.909803                      -0.945517   
3330               0.046617                       1.830239   
3331               0.586108                      -0.714204   
3332               1.017702                       1.367613   

      numPipe__total product detail views  numPipe__session duration  \
0                            4.750568e-01                  -0.079666   
1                            1.129111e+00                  -0.099387   
2                            6.763043e-01                  -1.578480   
3                           -1.487106e+00                  -2.742033   
4                            6.259924e-01                  -1.046007   
...                                   ...                        ...   
3328                        -1.185235e+00                   0.295038   
3329                         7.149746e-16                  -0.947401   
3330                         4.247450e-01                   1.734688   
3331                         2.234975e-01                  -0.809352   
3332                         6.259924e-01                   1.281100   

      numPipe__pr

# Model training 

In [75]:
x_train,x_test,y_train,y_test = train_test_split(x2,y,test_size=0.2,random_state=32)

In [76]:
adc = AdaBoostClassifier()
svc =  SVC()
knc = KNeighborsClassifier()
dtc = DecisionTreeClassifier()
rfc = RandomForestClassifier()


In [77]:
models = [adc,svc,knc,dtc,rfc]

for i in models:
    i.fit(x_train,y_train)
    
    y_pred_train = i.predict(x_train)
    y_pred = i.predict(x_test)
    
    tr=round(f1_score(y_pred_train,y_train),2)
    ts=round(f1_score(y_pred,y_test),2)
    
    print('*'*50)
    print(i)
    print('Trining F1 score:',tr)
    print('Testing F1 score:',ts)
  

**************************************************
AdaBoostClassifier()
Trining F1 score: 0.5
Testing F1 score: 0.48
**************************************************
SVC()
Trining F1 score: 0.73
Testing F1 score: 0.53
**************************************************
KNeighborsClassifier()
Trining F1 score: 0.52
Testing F1 score: 0.33
**************************************************
DecisionTreeClassifier()
Trining F1 score: 1.0
Testing F1 score: 0.69
**************************************************
RandomForestClassifier()
Trining F1 score: 1.0
Testing F1 score: 0.8


In [78]:
# here the best algorithm for classification come out to be  Adaboost classifier

## Hyperparameter tuning for best algorithm

In [79]:
grid = {
    'n_estimators':range(2,250)
}

In [80]:
rs = RandomizedSearchCV(adc,param_distributions=grid,cv=5)

rs.fit(x_train,y_train)

RandomizedSearchCV(cv=5, estimator=AdaBoostClassifier(),
                   param_distributions={'n_estimators': range(2, 250)})

In [81]:
adc1 = rs.best_estimator_

In [82]:
adc1

AdaBoostClassifier(n_estimators=173)

In [83]:
# Evaluation

def Evaluation(actual,pred):
    accu = accuracy_score(actual,pred)
    cfm = confusion_matrix(actual,pred)
    ftr = round(f1_score(actual,pred),2)
    fts = round(f1_score(actual,pred),2)
    print('_'*30)
    print('Accuracy:',accu)
    print('matrix\n',cfm)
    print('_'*30)
    print('Train-F1:',ftr)
    print('Test-F1:',fts)

In [84]:
y_pred1 = adc1.predict(x_train)
y_pred2 = adc1.predict(x_test)

Evaluation(y_train,y_pred1)
Evaluation(y_test,y_pred2)

______________________________
Accuracy: 0.8889722430607652
matrix
 [[2221   60]
 [ 236  149]]
______________________________
Train-F1: 0.5
Test-F1: 0.5
______________________________
Accuracy: 0.8710644677661169
matrix
 [[548  21]
 [ 65  33]]
______________________________
Train-F1: 0.43
Test-F1: 0.43


In [92]:
df = dataLoader('../Data/testing_ecommerce.csv')
df.shape

(1000, 19)

In [101]:
def Prediction(path,pipe,model):
    
    data = pd.read_csv(path)
    # x = data.drop(['churn'],axis=1)
    # y = data['churn']
    # Preprocess the data
    x1 = pd.DataFrame(pipe.transform(data),columns=pipe.get_feature_names_out())

    pred = model.predict(x1)

    return pred

In [102]:
Pred = Prediction('../Data/testing_ecommerce.csv',pipeline,adc1)
Pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,

In [103]:
result = df[['user id']]
result

user id
0    3802929
1    3895988
2    4067737
3    4218141
4    4042871
..       ...
995  3312144
996  3573187
997  4205990
998  3738900
999  3485728

[1000 rows x 1 columns]

In [105]:
result['Pred Churn'] = Pred
result


C:\Users\Ankush\AppData\Local\Temp\ipykernel_8776\2801972914.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result['Pred Churn'] = Pred


user id  Pred Churn
0    3802929           0
1    3895988           0
2    4067737           0
3    4218141           0
4    4042871           0
..       ...         ...
995  3312144           0
996  3573187           0
997  4205990           0
998  3738900           0
999  3485728           0

[1000 rows x 2 columns]

In [106]:
result.to_csv('Prediction.csv')